### DISCUSSION TITLE
v2 config valid fail ('OpenpaiConfig: trial_cpu_number is not set')

### DISCUSSION THREAD

**Discussion by 666XD** [microsoft/nni#3800] [Q&A] [answered]
**Describe the issue**:

Using v2 config on pai and get the following error.
`ERROR: Config V2 validation failed: ValueError('OpenpaiConfig: trial_cpu_number is not set')`
`ERROR: 'NoneType' object has no attribute 'get'`

But I can't find a way to set the trial CPU number on v2 config.

**Environment**: ubuntu 18
- NNI version: 2.2
- Training service (local|remote|pai|aml|etc): pai
- Python version: 3.8.2
- Is running in Docker?: yes

**Configuration**:
```
searchSpaceFile: searchSpace.json
trialCodeDirectory: .
trialCommand: python3 mnist.py
trialConcurrency: 3
trialGpuNumber: 1
maxTrialNumber: 12
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: "openpai"
  host: "http://172.16.1.16"
  token: 'xxxxxxxxxxx'
  username: 'admin'
  localStorageMountPoint: '~/'
  containerStorageMountPoint: '~/'
```

**Comment by ultmaster** [comment]
You can set `trialCpuNumber` in `trainingService`. It's missing in docs. We will update soon.

**Comment by 666XD** [comment]
It's worked!  Thanks!

And I found that 
* `localStorageMountPoint`
* `trial_memory_size`
* `storage_config_name`

are also request for PAI mode or it will fail on the validation part, but it does not appear in the docs too.
And what does `localStorageMountPoint` used for?

Besides, `nniManagerStorageMountPoint` seens not working correctly.
I get this message 
`ERROR: Config V2 validation failed: ValueError('OpenpaiConfig: Unrecognized fields nnimanagerstoragemountpoint')` 
when I add it to the config.

Here's how my config_v2 looks right now:
```
searchSpaceFile: searchSpace.json
trialCodeDirectory: .
trialCommand: python3 mnist.py
trialConcurrency: 3
trialGpuNumber: 1
maxTrialNumber: 12
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: "openpai"
  host: "http://172.16.1.16"
  username: "admin"
  token: "xxxxxxxxx"
  # nniManagerStorageMountPoint: '/some/path' # !Error
  localStorageMountPoint: '/some/path' #?? what is this for?
  containerStorageMountPoint: '/some/path'
  trialCpuNumber: 8
  trial_memory_size: 1024
  openpaiConfig:
  storage_config_name: 'some name'
```

Really looking for the PAI tutorial for v2 config~
