### ISSUE TITLE
Problem running NNI with FrameworkController on Minikube cluster

### ISSUE THREAD

**Issue by anhdo1303** [microsoft/nni#1156]
**Short summary about the issue/question**:

I was able to run my sample script (simple Tensorflow model) with `trainingServicePlatform=local`, but I encountered error with `frameworkController`

I followed [this doc](https://github.com/microsoft/nni/blob/master/docs/en_US/FrameworkControllerMode.md)
- Minikube cluster running
- kubeconfig is correct. Running **kubectl** commands works
- nnictl script somehow keep asking for the password, and timeout after a bit

Here is the output log
```
> nnictl create --config ./config_kubeflow.yml
INFO: expand searchSpacePath: search_space.json to /path/to/search_space.json 
INFO: expand codeDir: . to /path/to/. 
INFO: Starting restful server...
INFO: Successfully started Restful server!
INFO: Setting frameworkcontroller config...
Password:ERROR: Failed! Error is: {"error":"TrainingService setClusterMetadata timeout. Please check your config file."}
```

**nni Environment**:
- nni version: 0.7
- nni mode(local|pai|remote): frameworkcontroller
- OS: macOS
- python version: 3.7.2
- is conda or virtualenv used?: virtualenv
- is running in docker?: no

**Comment by SparkSnail** [comment]
Hi, this problem might caused by the storage initialize error. NNI support using NFS and AzureStorage as the volume on Kubernetes, which storage did you choose?
If you use NFS server as the storage, please make sure the `nfsServer:nfsPath` is correct, and input correct password, for NNI will use `sudo mount nfsServer:nfsPath temPath` command to mount the nfs path to a temp folder used in NNI experiment. Refer https://github.com/microsoft/nni/blob/master/src/nni_manager/training_service/kubernetes/kubernetesTrainingService.ts#L217.

**Comment by anhdo1303** [comment]
@SparkSnail Thank you for the clarification. I setup the NFS server locally on my Mac.
Must be something wrong/typo the when I did it. I redo and it is working now.

Thank you, and I will close this issue.

**Comment by husimple** [comment]
@SparkSnail I also enconter this problem:
ERROR: Failed! Error is: {"error":"TrainingService setClusterMetadata timeout. Please check your config file."}
my experiment running in docker and nni mode is remote.my config.yml as fllows:
authorName: default
experimentName: example_mnist
trialConcurrency: 2
maxExecDuration: 1h
maxTrialNum: 20
#choice: local, remote, pai, kubeflow
trainingServicePlatform: remote
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
assessor:
  builtinAssessorName: Medianstop
  classArgs:
    optimize_mode: maximize
  gpuNum: 0
trial:
  command: python3 mnist.py
  codeDir: .
  gpuNum: 0
machineList:
  - ip: 17.2.0.4/16
    username: yjt
    port: 20
    sshKeyPath: /root/.ssh/id_rsa
  - ip: 17.2.0.3/16
    username: yjtr
    port: 20
    sshKeyPath: /root/.ssh/id_rsa

**Comment by justttry** [comment]
I met the same problem. @husimple. Do you solve it?

**Comment by ragavvenkatesan** [comment]
+1

**Comment by SparkSnail** [comment]
@ragavvenkatesan could you provide more information about the experiment?

**Comment by ragavvenkatesan** [comment]
> @ragavvenkatesan could you provide more information about the experiment?

Sure. So I have a cluster with a master and two remotes. I am running the nnictl create with a config file on the master. My config file looks as follows:

``` 
authorName: ----
experimentName: distributed_mnist_demo
trialConcurrency: 16
maxExecDuration: 1h
maxTrialNum: 160
#choice: local, remote, pai
trainingServicePlatform: remote
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
logLevel: debug
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: GPTuner
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python3 mnist-nni.py
  codeDir: .
  gpuNum: 1
machineList:
  - ip: ----
    username: ----
    sshKeyPath: ----
    gpuIndices: 0,1,2,3
  - ip: ----
    username: ----
    sshKeyPath: ----
    gpuIndices: 0,1,2,3
````

In either of the remotes, I am able to validate that I can run nni (same code, search space etc) in local mode and port forward webui to the master. I can also ssh into the remotes using the master with the exact same sshKeyPath no problem. When I run the remote job on the master I get the following log on the nnimanager.log file.

```
[4/29/2020, 9:47:55 PM] DEBUG [ 'Database directory: ----/nni/experiments/TlGzaUnb/db' ]
[4/29/2020, 9:47:55 PM] INFO [ 'Datastore initialization done' ]
[4/29/2020, 9:47:55 PM] INFO [ 'RestServer start' ]
[4/29/2020, 9:47:55 PM] INFO [ 'Construct remote machine training service.' ]
[4/29/2020, 9:47:55 PM] INFO [ 'RestServer base port is 8080' ]
[4/29/2020, 9:47:55 PM] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[4/29/2020, 9:47:57 PM] DEBUG [ 'GET: /check-status: body:\n{}' ]
[4/29/2020, 9:47:57 PM] DEBUG [ 'PUT: /experiment/cluster-metadata: body:\n{\n    "machine_list": [\n        {\n            "ip": "----",\n            "username": "----",\n            "sshKeyPath": "----,\n            "gpuIndices": "0,1,2,3",\n            "port": 22\n        },\n        {\n            "ip": "----",\n            "username": "----",\n            "sshKeyPath": "----",\n            "gpuIndices": "0,1,2,3",\n            "port": 22\n        }\n    ]\n}' ]
[4/29/2020, 9:47:57 PM] INFO [ 'NNIManager setClusterMetadata, key: machine_list, value: [{"ip":"----","username":"----","sshKeyPath":"----","gpuIndices":"0,1,2,3","port":22},{"ip":"----","username":"----","sshKeyPath":"----","gpuIndices":"0,1,2,3","port":22}]' ]
[4/29/2020, 9:47:57 PM] DEBUG [ 'Connecting to remote machines: [{"ip":"----","username":"----","sshKeyPath":"----","gpuIndices":"0,1,2,3","port":22},{"ip":"----","username":"----","sshKeyPath":"----","gpuIndices":"0,1,2,3","port":22}]' ]
[4/29/2020, 9:48:07 PM] FATAL [ { Error: TrainingService setClusterMetadata timeout. Please check your config file.
      at Timeout.setTimeout (----/nni/core/nnimanager.js:181:51)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)
    name: '',
    cause:
     Error: TrainingService setClusterMetadata timeout. Please check your config file.
         at Timeout.setTimeout (----/nni/core/nnimanager.js:181:51)
         at ontimeout (timers.js:436:11)
         at tryOnTimeout (timers.js:300:5)
         at listOnTimeout (timers.js:263:5)
         at Timer.processTimers (timers.js:223:10) } ]
```
I do not generate any other log files (redatcted ips etc). Please advice. Thank you.
