### ISSUE TITLE
Same configurations are tested multiple times

### ISSUE THREAD

**Issue by martsalz** [microsoft/nni#1474]
**Short summary about the issue/question**:

If NNI is running on its own neural network, identical configurations are tested multiple times.

**Brief what process you are following**: 

**How to reproduce it**: 

Execute the following command and observe the progress in the webinterface:

`nnictl  create --config nni/examples/trials/mnist-keras/config.yml`

In my example, the following search space is available:

```
{
    "optimizer":{"_type":"choice","_value":["Adam", "RMSprop"]},
    "learning_rate":{"_type":"choice","_value":[0.0001, 0.001, 0.002, 0.005, 0.01]}
}
```

**nni Environment**:
- nni version: 0.9.1.1
- nni mode(local|pai|remote): remote
- OS: CentOS Linux 7
- python version: Python 3.6
- is conda or virtualenv used?: virtualenv
- is running in docker?: no

**need to update document(yes/no)**: no

**Anything else we need to know**:

![image](https://user-images.githubusercontent.com/12211578/63149862-99402c80-c005-11e9-9593-244105007643.png)

config.yml:

```
authorName: default
experimentName: example_mnist
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: remote
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: Random
  classArgs:
    #choice: maximize, minimize
    #optimize_mode: maximize
trial:
  command: python test.py
  codeDir: .
  gpuNum: 0
machineList:
  - ip: <Machine_2_IP>
    username: <username>
    passwd: <passwd>
    #port can be skip if using default ssh port 22
    #port: 22
nniManagerIp: <Machine_1_IP>
```
