### ISSUE TITLE
Hyperband Algorithm Example Reproduction

### ISSUE THREAD

**Issue by martsalz** [microsoft/nni#1567]
**Short summary about the issue/question**:

Currently I use the Hyperband algorithm. By the way, the example under `examples/trials/mnist-hyperband/` is not included in the master branch as mentioned in the documentation.

I summed up all n values from the table `(81+27+9+3+1+27+9+3+1+9+3+1+6+2+5)` and set them as `maxTrialNum = 187`. For `s = 4` NNI produces the same values as given in the table. From `s = 3` NNI behaves differently. For the 0th iteration, `n = 27` is specified in the table. Here, NNI creates a total of 34 instead of 27 trials. For the 1st iteration (`s = 3`) 11 instead of 9. For the 2nd and 3rd iterations the n values of NNI match the table again.

How can I reproduce the listed table?

**nni Environment**:
- nni version: v0.8-320-g421065b
- nni mode(local|pai|remote): local
- OS: CentOS Linux 7
- python version: Python 3.6
- is conda or virtualenv used?: virtualenv 
- is running in docker?: no

**Anything else we need to know**:

https://arxiv.org/pdf/1603.06560.pdf
https://github.com/microsoft/nni/blob/master/docs/en_US/Tuner/HyperbandAdvisor.md

![image](https://user-images.githubusercontent.com/12211578/65495028-4a17d200-deb6-11e9-9f14-093cb819f6af.png)
![image](https://user-images.githubusercontent.com/12211578/65495051-556afd80-deb6-11e9-83cd-4c10d96303d9.png)

```
authorName: default
experimentName: example_mnist
trialConcurrency: 1
maxExecDuration: 72h
maxTrialNum: 187
localConfig:
    useActiveGpu: true
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
advisor:
  #choice: Hyperband
  builtinAdvisorName: Hyperband
  classArgs:
    #R: the maximum STEPS (could be the number of mini-batches or epochs) can be
    #   allocated to a trial. Each trial should use STEPS to control how long it runs.
    R: 81
    #eta: proportion of discarded trials
    eta: 3
    #choice: maximize, minimize
    optimize_mode: minimize
trial:
  command: python3 test.py
  codeDir: .
  gpuNum: 1
```
