### ISSUE TITLE
BOHB Tuner: TUNER_NO_MORE_TRIAL

### ISSUE THREAD

**Issue by martsalz** [microsoft/nni#1593]
**Short summary about the issue/question**:

When I execute the MNIST BOHB tuner example with NNI, the status changes to `TUNER_NO_MORE_TRIAL ` after a few trials. However, the status changes back to `RUNNING ` after a few seconds and the experiment continues. 

What does the status `TUNER_NO_MORE_TRIAL ` mean?
Why does this status appear in the BOHB MINIST example?

https://github.com/microsoft/nni/tree/master/examples/trials/mnist-advisor

**Brief what process you are following**: 

**How to reproduce it**: 

I have modified the `config_bohb.yml` slightly so that the GPU is used. I have added/changed the following lines:

```
trialConcurrency: 2
localConfig:
    useActiveGpu: true
trial:
   gpuNum: 1
```

**nni Environment**:
- nni version: v1.0-28-gf1210a9
- nni mode(local|pai|remote): local
- OS: CentOS 7
- python version: Python 3.6
- is conda or virtualenv used?: virtualenv 
- is running in docker?: no

**Anything else we need to know**:

```
authorName: default
experimentName: example_mnist_bohb
trialConcurrency: 2
maxExecDuration: 10h
maxTrialNum: 1000
localConfig:
    useActiveGpu: true
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
advisor:
  #choice: Hyperband, BOHB
  #(BOHB should be installed through nnictl)
  builtinAdvisorName: BOHB
  classArgs:
    max_budget: 27
    min_budget: 1
    eta: 3
    optimize_mode: maximize
trial:
  command: python3 mnist.py
  codeDir: .
  gpuNum: 1
```

![image](https://user-images.githubusercontent.com/12211578/66463293-1b385900-ea7d-11e9-918e-51607cfbbc6d.png)
