### ISSUE TITLE
setClusterMetadata timeout with remote mode using sshKey

### ISSUE THREAD

**Issue by justttry** [microsoft/nni#1608]
**Short summary about the issue/question**:
Below is the error:
```
[10/14/2019, 7:34:01 PM] INFO [ 'Datastore initialization done' ]
[10/14/2019, 7:34:01 PM] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[10/14/2019, 7:34:01 PM] INFO [ 'RestServer start' ]
[10/14/2019, 7:34:01 PM] INFO [ 'Construct remote machine training service.' ]
[10/14/2019, 7:34:01 PM] INFO [ 'RestServer base port is 8080' ]
[10/14/2019, 7:34:04 PM] INFO [ 'NNIManager setClusterMetadata, key: machine_list, value: [{"ip":"172.17.0.2","username":"root","sshKeyPath":"/root/.ssh/id_rsa","useActiveGpu":true,"port":22}]' ]
[10/14/2019, 7:34:14 PM] FATAL [ { Error: TrainingService setClusterMetadata timeout. Please check your config file.
      at Timeout.setTimeout (/root/nni/core/nnimanager.js:150:51)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)
    name: '',
    cause:
     Error: TrainingService setClusterMetadata timeout. Please check your config file.
         at Timeout.setTimeout (/root/nni/core/nnimanager.js:150:51)
         at ontimeout (timers.js:436:11)
         at tryOnTimeout (timers.js:300:5)
         at listOnTimeout (timers.js:263:5)
         at Timer.processTimers (timers.js:223:10) } ]
```

**Brief what process you are following**: 

**How to reproduce it**: 
Run nnictl in docker with remote mode using sshKey.

**nni Environment**:
- nni version: v1.0
- nni mode(local|pai|remote): remote
- OS: ubuntu16.04
- python version: 3.7
- is conda or virtualenv used?:  anaconda
- is running in docker?: yes

**need to update document(yes/no)**:

**Anything else we need to know**:
Here is my configs

```
authorName: default
experimentName: example_pytorch_cifar10
trialConcurrency: 12
maxExecDuration: 1000h
maxTrialNum: 1000
#choice: local, remote, pai
trainingServicePlatform: remote
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: /root/anaconda3/bin/python3 main.py
  codeDir: .
  gpuNum: 1
#localConfig:
#  maxTrialNumPerGpu:  2
machineList:
  - ip: 172.17.0.2
    username: root
    sshKeyPath: /root/.ssh/id_rsa
    useActiveGpu: true
```
