### ISSUE TITLE
"error":"TrainingService setClusterMetadata timeout. Please check your config file."

### ISSUE THREAD

**Issue by Guptajakala** [microsoft/nni#1619]
**Short summary about the issue/question**:
When creating a job on remote, I met this error 
`"error":"TrainingService setClusterMetadata timeout. Please check your config file."`

**Brief what process you are following**: 
My config.yml file is like below.
```
authorName: default
experimentName: example_pytorch_cifar10
trialConcurrency: 4
maxExecDuration: 100h
maxTrialNum: 100
#choice: local, remote, pai
trainingServicePlatform: remote
searchSpacePath: search_space.json
logDir: .....
logLevel: trace
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
assessor:
  #choice: Medianstop
  builtinAssessorName: Medianstop
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
    start_step: 50
trial:
  command: python main.py
  codeDir: .
  gpuNum: 1
machineList:
  - ip: .....
    port: 22
    username: ......
    passwd: ....
    gpuIndices: 0,1,2,3
    maxTrialNumPerGpu: 1
    useActiveGpu: true
  - ip: .....
    port: 22
    username: ......
    passwd: ....
    gpuIndices: 0,1,2,3
    maxTrialNumPerGpu: 1
    useActiveGpu: true
```
And then start the experiment
`nnictl creat --config config.yml`

**How to reproduce it**: 

**nni Environment**:
- nni version: latest
- nni mode(local|pai|remote): remote
- OS: Ubuntu16
- python version: 3.6
- is conda or virtualenv used?:  conda
- is running in docker?: NO

**need to update document(yes/no)**:
NO

**Anything else we need to know**:
I have manually verified the ssh IP and PWD are valid by ssh login.
Additionally I added some print out in [launcher.py](https://github.com/microsoft/nni/blob/99f7d79c7e772f7c58415b459db95fa9cd09b273/tools/nni_cmd/launcher.py#L186) And found the problem locates in [rest_put](https://github.com/microsoft/nni/blob/99f7d79c7e772f7c58415b459db95fa9cd09b273/tools/nni_cmd/launcher.py#L195). Debug output:
```
running rest_put...
cluster_metadata_url(port): http://localhost:8080/api/v1/nni/experiment/cluster-metadata
```
Another thing is I also tried to set the "nniManagerIp" using the same IP address as the first machine in the machine list. It still does not work.

I have not found any example which successfully run remote mode. Please help, thanks!
