### ISSUE TITLE
Missing key: 'sshKeyPath'

### ISSUE THREAD

**Issue by forhonourlx** [microsoft/nni#1928]
Hi, 
I am trying ssh remote mode on Ubuntu NNI1.3:
```
machineList:
  - ip: 192.168.1.102
    username: simon
    passwd: 1
    #port can be skip if using default ssh port 22
    port: 22
  - ip: 192.168.1.3
    username: simon
    passwd: 1
    port: 22
```
Got:
```
Missing key: 'sshKeyPath'
```
Could somebody help?
Thanks in advance.

**Comment by SparkSnail** [comment]
Hi @forhonourlx , could you try using 
```
machineList:
  - ip: 192.168.1.102
    username: simon
    passwd: "1"
    #port can be skip if using default ssh port 22
    port: 22
  - ip: 192.168.1.3
    username: simon
    passwd: "1"
    port: 22
```
This problem might caused by the value type of passwd, the pure digital numbers in passwd might be recognized as `Number` type, since NNI only support `String` type in passwd field.
