### ISSUE TITLE
No data in Default metric

### ISSUE THREAD

**Issue by Sundrops** [microsoft/nni#1939]
I want to run comands of trial in a docker container. And I found the metics in /mnt/share/alex/nni/experiment/xxxx/trials/xxxxx/.nni/metrics after I run `nnictl create --config config.yaml`. But, they were not shown in Default metric(WebUI). 
```yaml
authorName: default
experimentName: example_mnist_pytorch
trialConcurrency: 2
maxExecDuration: 1h
maxTrialNum: 40
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
logDir: /mnt/share/alex/nni/experiment
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
trial:
# /mnt/share is a share dir(local and container both can access it)
  command: run my docker xxxx -c "python /mnt/share/alex/projects/nni/examples/mnist-pytorch/mnist.py
  codeDir: .
  gpuNum: 1
```
```
ME000098{"parameter_id": 2, "trial_job_id": "atKaa", "type": "PERIODICAL", "sequence": 0, "value": 31.56}
ME000098{"parameter_id": 2, "trial_job_id": "atKaa", "type": "PERIODICAL", "sequence": 1, "value": 58.88}
ME000098{"parameter_id": 2, "trial_job_id": "atKaa", "type": "PERIODICAL", "sequence": 2, "value": 68.79}
ME000098{"parameter_id": 2, "trial_job_id": "atKaa", "type": "PERIODICAL", "sequence": 3, "value": 71.58}
ME000098{"parameter_id": 2, "trial_job_id": "atKaa", "type": "PERIODICAL", "sequence": 4, "value": 77.17}
ME000098{"parameter_id": 2, "trial_job_id": "atKaa", "type": "PERIODICAL", "sequence": 5, "value": 81.07}
ME000098{"parameter_id": 2, "trial_job_id": "atKaa", "type": "PERIODICAL", "sequence": 6, "value": 83.97}
ME000098{"parameter_id": 2, "trial_job_id": "atKaa", "type": "PERIODICAL", "sequence": 7, "value": 85.91}
ME000097{"parameter_id": 2, "trial_job_id": "atKaa", "type": "PERIODICAL", "sequence": 8, "value": 87.1}
ME000093{"parameter_id": 2, "trial_job_id": "atKaa", "type": "FINAL", "sequence": 0, "value": 88.04}

```
![image](https://user-images.githubusercontent.com/14829222/72073963-f5e11280-332b-11ea-9bee-ee935172a0f8.png)
