### ISSUE TITLE
Failed to submit trail with http code 500

### ISSUE THREAD

**Issue by ICEORY** [microsoft/nni#2016]
**nni Environment**:
- nni version: 1.3
- nni mode(local|pai|remote): pai 0.14
- OS: ubuntu  16.04
- python version: 3.6
- is conda or virtualenv used?: anaconda
- is running in docker?: no

**log** 
```
[2/8/2020, 2:48:24 PM] ERROR [ 'Submit trial JHmXB failed, http code:500, http body: {"message":"Request failed with status code 400"}' ]
[2/8/2020, 2:48:27 PM] DEBUG [ 'ipcInterface command type: [PI], content:[]' ]
[2/8/2020, 2:48:28 PM] DEBUG [ 'GET: /experiment: body:\n{}' ]
[2/8/2020, 2:48:28 PM] DEBUG [ 'GET: /check-status: body:\n{}' ]
[2/8/2020, 2:48:28 PM] DEBUG [ 'GET: /trial-jobs: body:\n{}' ]
[2/8/2020, 2:48:28 PM] DEBUG [ 'getTrialJobsByReplayEvents begin' ]
[2/8/2020, 2:48:28 PM] DEBUG [ 'getTrialJobsByReplayEvents done' ]
[2/8/2020, 2:48:28 PM] DEBUG [ 'GET: /metric-data: body:\n{}' ]
[2/8/2020, 2:48:28 PM] DEBUG [ 'GET: /experiment: body:\n{}' ]
[2/8/2020, 2:48:28 PM] DEBUG [ 'GET: /trial-jobs: body:\n{}' ]
[2/8/2020, 2:48:28 PM] DEBUG [ 'GET: /metric-data: body:\n{}' ]
[2/8/2020, 2:48:28 PM] DEBUG [ 'getTrialJobsByReplayEvents begin' ]
[2/8/2020, 2:48:28 PM] DEBUG [ 'getTrialJobsByReplayEvents done' ]
[2/8/2020, 2:48:28 PM] DEBUG [ 'GET: /version: body:\n{}' ]
```
![image](https://user-images.githubusercontent.com/11911903/74080932-e5839b00-4a83-11ea-8331-c80ade8294e8.png)

**more information**
- trail num: 5
- nni <= 1.2 works fine with the same configurations.

**Comment by SparkSnail** [comment]
Hi @ICEORY, what is your running mode?

**Comment by ICEORY** [comment]
- config.yml
```
authorName: iceory
logDir: /media/nni
experimentName: debug_nni
trialConcurrency: 5
maxExecDuration: 10h
maxTrialNum: 5
trainingServicePlatform: pai
useAnnotation: true
nniManagerIp: 10.10.xxx.xxx 
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
trial:
  command: echo hostname
  codeDir: ./
  gpuNum: 1
  cpuNum: 4
  memoryMB: 8000
  virtualCluster: default
  image: my_nni_docker 
  containerNFSMountPath: /ssd/iceory/nni_container # nni >=1.3
  nniManagerNFSMountPath: /media/nni # nni >= 1.3
  paiStoragePlugin: team_wise # nni >= 1.3

paiConfig:
  userName: ******
  passWord: ******
  host: 192.168.xxx.xxx
```
