### ISSUE TITLE
Several complaints/limitations/workarounds for NNI on PAI K8S

### ISSUE THREAD

**Issue by ultmaster** [microsoft/nni#2147]
1. Why `ls $NNI_SYS_DIR`?
https://github.com/microsoft/nni/blob/2e42d1d8beed186f85271c660cdc9d2c1c49580d/src/nni_manager/training_service/pai/paiK8S/paiK8SData.ts#L34

2. `nni_log` doesn't flush. Log can be sometimes missing (still in buffer). Very confusing.
https://github.com/microsoft/nni/blob/2e42d1d8beed186f85271c660cdc9d2c1c49580d/tools/nni_trial_tool/log_utils.py#L39

3. Deep merge has problems.
https://github.com/microsoft/nni/blob/2e42d1d8beed186f85271c660cdc9d2c1c49580d/src/nni_manager/training_service/pai/paiK8S/paiK8STrainingService.ts#L199
In case user wants to have ssh plugin in his/her config, they will write:
```yaml
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: ssh
      parameters:
        jobssh: true
```
but this is not found in the final config, because plugin already has
```yaml
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: teamwise_storage
```

4. It seems that NNI encourages users to write config with NNI config, instead of merging with existing config, which is quite opposite of the usual way (develop and train a model on PAI, then finetune it with NNI). This is just a complaint.

5. Due to the overwrite machanism, it's not possible to use more than 1 instance (e.g., multi-machine training) on PAI, because NNI hardcoded it as 1. Any customization with custom config file will be overwritten.
https://github.com/microsoft/nni/blob/2e42d1d8beed186f85271c660cdc9d2c1c49580d/src/nni_manager/training_service/pai/paiK8S/paiK8STrainingService.ts#L161
Similar problem exists for users who try to open multiple taskroles, or customize a job name, or add some commands before trial keeper actually starts (though these are not my requests). It seems the "config merging" is quite limited. In fact, the only 2 options that I find merging useful are `shmMB` and `port`.
