### ISSUE TITLE
Issue in understanding WebUI

### ISSUE THREAD

**Issue by anandhperumal** [microsoft/nni#2342]
As my trialConcurrency is set to 3 and I only see the 3 trails in WebUI and even in the log folder.
I believe 3 trails indicate the concurrency, later other trails should begin after this but I don't see any logs nor in the WebUI

**Short summary about the issue/question**:
I have defined a search space with the following details:
```
{

    "lr":{"_type":"choice","_value":[0.000000001, 0.00000001, 0.0000001, 0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1]},
    "epochs":{"_type":"choice","_value":[5, 10, 15, 20]},
    "save_checkpoints_dir":{"_type":"choice","_value":["models"]},
    "device":{"_type":"choice","_value":["cuda"]},
    "flag":{"_type":"choice","_value":[0]},
    "save_best":{"_type":"choice","_value":[3]},
    "log_interval":{"_type":"choice","_value":[250]},
    "optimizer":{"_type":"choice","_value":["AdamW"]}
}

```
and my config file looks like this :
```
authorName: default
experimentName: run-QQC
trialConcurrency: 3
maxExecDuration: 24h
maxTrialNum: 100
#choice: local, remote, pai
#trainingServicePlatform: local
trainingServicePlatform: remote
searchSpacePath: package.json
#choice: true, false
useAnnotation: false
tuner:
#  codeDir: ~/nni/src/sdk/pynni/nni/pbt_tuner
#  classFileName: pbt_tuner.py
#  className: PBTTuner
  builtinTunerName: PBTTuner
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python run.py
  codeDir: .
  gpuNum: 1
assessor:
    builtinAssessorName: Curvefitting
    classArgs:
      epoch_num: 20
      optimize_mode: maximize
      start_step: 6
      threshold: 0.95
      gap: 1

```
**Brief what process you are following**: 

**How to reproduce it**: 

**nni Environment**:
- nni version:1.4
- nni mode(local|pai|remote):local
- OS: Windows 10
- python version: 3.7
- is conda or virtualenv used?: no 
- is running in docker?: no

**need to update document(yes/no)**:

**Anything else we need to know**:
