### ISSUE TITLE
SSH Timeout error.

### ISSUE THREAD

**Issue by ragavvenkatesan** [microsoft/nni#2400]
**Short summary about the issue/question**:
I am unable to work on remote mode using Amazon ec2 clusters.

**Brief what process you are following**: 
So I have a cluster with a master and two remotes. I am running the nnictl create with a config file on the master. My config file looks as follows:
```
authorName: ----
experimentName: distributed_mnist_demo
trialConcurrency: 16
maxExecDuration: 1h
maxTrialNum: 160
#choice: local, remote, pai
trainingServicePlatform: remote
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
logLevel: debug
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: GPTuner
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python3 mnist-nni.py
  codeDir: .
  gpuNum: 1
machineList:
  - ip: ----
    username: ----
    sshKeyPath: ----
    gpuIndices: 0,1,2,3
  - ip: ----
    username: ----
    sshKeyPath: ----
    gpuIndices: 0,1,2,3
```
In either of the remotes, I am able to validate that I can run nni (same code, search space etc) in local mode and port forward webui to the master. I can also ssh into the remotes using the master with the exact same sshKeyPath no problem. When I run the remote job on the master I get the following log on the nnimanager.log file.

```
[4/29/2020, 9:47:55 PM] DEBUG [ 'Database directory: ----/nni/experiments/TlGzaUnb/db' ]
[4/29/2020, 9:47:55 PM] INFO [ 'Datastore initialization done' ]
[4/29/2020, 9:47:55 PM] INFO [ 'RestServer start' ]
[4/29/2020, 9:47:55 PM] INFO [ 'Construct remote machine training service.' ]
[4/29/2020, 9:47:55 PM] INFO [ 'RestServer base port is 8080' ]
[4/29/2020, 9:47:55 PM] INFO [ 'Rest server listening on: http://0.0.0.0:8080' ]
[4/29/2020, 9:47:57 PM] DEBUG [ 'GET: /check-status: body:\n{}' ]
[4/29/2020, 9:47:57 PM] DEBUG [ 'PUT: /experiment/cluster-metadata: body:\n{\n    "machine_list": [\n        {\n            "ip": "----",\n            "username": "----",\n            "sshKeyPath": "----,\n            "gpuIndices": "0,1,2,3",\n            "port": 22\n        },\n        {\n            "ip": "----",\n            "username": "----",\n            "sshKeyPath": "----",\n            "gpuIndices": "0,1,2,3",\n            "port": 22\n        }\n    ]\n}' ]
[4/29/2020, 9:47:57 PM] INFO [ 'NNIManager setClusterMetadata, key: machine_list, value: [{"ip":"----","username":"----","sshKeyPath":"----","gpuIndices":"0,1,2,3","port":22},{"ip":"----","username":"----","sshKeyPath":"----","gpuIndices":"0,1,2,3","port":22}]' ]
[4/29/2020, 9:47:57 PM] DEBUG [ 'Connecting to remote machines: [{"ip":"----","username":"----","sshKeyPath":"----","gpuIndices":"0,1,2,3","port":22},{"ip":"----","username":"----","sshKeyPath":"----","gpuIndices":"0,1,2,3","port":22}]' ]
[4/29/2020, 9:48:07 PM] FATAL [ { Error: TrainingService setClusterMetadata timeout. Please check your config file.
      at Timeout.setTimeout (----/nni/core/nnimanager.js:181:51)
      at ontimeout (timers.js:436:11)
      at tryOnTimeout (timers.js:300:5)
      at listOnTimeout (timers.js:263:5)
      at Timer.processTimers (timers.js:223:10)
    name: '',
    cause:
     Error: TrainingService setClusterMetadata timeout. Please check your config file.
         at Timeout.setTimeout (----/nni/core/nnimanager.js:181:51)
         at ontimeout (timers.js:436:11)
         at tryOnTimeout (timers.js:300:5)
         at listOnTimeout (timers.js:263:5)
         at Timer.processTimers (timers.js:223:10) } ]
```
I do not generate any other log files (redatcted ips etc). Please advice. Thank you.

**How to reproduce it**: 
**nni Environment**:
- nni version: 1.5
- nni mode(local|pai|remote): remote
- OS: Linux ubuntu
- python version: 3.6
- is conda or virtualenv used?: conda virtualenv.
- is running in docker?: no

**need to update document(yes/no)**:

**Anything else we need to know**:

**Log message**:
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 
Refer above

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) : 
Refer above.
