### ISSUE TITLE
Training Service Framework Controller - AKS - Frozen

### ISSUE THREAD

**Issue by seanytak** [microsoft/nni#2404]
**Short summary about the issue/question**:
I am trying to utilize the Framework Controller service with Azure Kubernetes Service. NNI does not report any errors but the training jobs never start on top of AKS. I have followed the [Framework Controller documentation to the best of my knowledge](https://github.com/microsoft/nni/blob/master/docs/en_US/TrainingService/FrameworkControllerMode.md). When I check the Azure File Share, the contents from `codeDir` are copied correctly but the `output` file from the `trial stdout` does not appear to exist. 

**Brief what process you are following**: 

I am attempting this as a fresh process with all Azure services being instantiated per the NNI Framework Controller documentation as well as the additional documentation from the Framework Controller github as well.

**How to reproduce it**: 

I followed the steps under `Prerequisite for Azure Kubernetes Service` and `Setup Framework Controller`. From the Framework Controller documentation, I followed `Run By Kubernetes StatefulSet`. I copied the commands as is and the yaml file as is only modifying the information in the config file for NNI. I created the job via `nnictl create --config frameworkcontroller_config.yaml --port 25565` (the default port was unusable due to another application on 8081). 

**nni Environment**:
- nni version: 1.5
- nni mode(local|pai|remote): frameworkcontroller
- OS: Ubuntu 18.04
- python version: 3.7.7
- is conda or virtualenv used?: conda
- is running in docker?: no

**need to update document(yes/no)**:
unsure

**Anything else we need to know**:

**Log message**:
 - [nnimanager.log and dispatcher.log](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/HowToDebug.md#experiment-root-directory) : 

dispatcher.log
```
[05/05/2020, 11:44:16 PM] INFO (hyperopt.utils/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[05/05/2020, 11:44:16 PM] INFO (hyperopt.fmin/MainThread) Failed to load dill, try installing dill via "pip install dill" for enhanced pickling support.
[05/05/2020, 11:44:16 PM] INFO (nni.msg_dispatcher_base/MainThread) Start dispatcher
[05/05/2020, 11:44:16 PM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000864 seconds
[05/05/2020, 11:44:16 PM] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
[05/05/2020, 11:44:16 PM] INFO (hyperopt.tpe/Thread-1) tpe_transform took 0.000768 seconds
[05/05/2020, 11:44:16 PM] INFO (hyperopt.tpe/Thread-1) TPE using 0 trials
```

nnimanager.log
```
[5/5/2020, 11:44:12 PM] INFO [ 'Datastore initialization done' ]
[5/5/2020, 11:44:12 PM] INFO [ 'RestServer start' ]
[5/5/2020, 11:44:12 PM] INFO [ 'RestServer base port is 25565' ]
[5/5/2020, 11:44:12 PM] INFO [ 'Rest server listening on: http://0.0.0.0:25565' ]
[5/5/2020, 11:44:14 PM] INFO [ 'NNIManager setClusterMetadata, key: frameworkcontroller_config, value: {"storage":"azureStorage","keyVault":{"vaultName":"nni","name":"nnikey"},"azureStorage":{"accountName":"nnistorage","azureShare":"ncf"}}' ]
[5/5/2020, 11:44:16 PM] INFO [ 'NNIManager setClusterMetadata, key: trial_config, value: {"codeDir":"/home/setakafu/projects/100DaysML/src/recommenders/.","taskRoles":[{"name":"worker","taskNum":1,"command":"python3 train_ncf.py","gpuNum":1,"cpuNum":1,"memoryMB":8192,"image":"msranni/nni:latest","frameworkAttemptCompletionPolicy":{"minFailedTaskCount":1,"minSucceededTaskCount":1}}]}' ]
[5/5/2020, 11:44:16 PM] INFO [ 'Starting experiment: lbYvXQ4f' ]
[5/5/2020, 11:44:16 PM] INFO [ 'Change NNIManager status from: INITIALIZED to: RUNNING' ]
[5/5/2020, 11:44:16 PM] INFO [ 'Add event listeners' ]
[5/5/2020, 11:44:16 PM] INFO [ 'RestServer start' ]
[5/5/2020, 11:44:16 PM] INFO [ 'RestServer base port is 25566' ]
[5/5/2020, 11:44:16 PM] INFO [ 'frameworkcontroller Training service rest server listening on: http://0.0.0.0:25566' ]
[5/5/2020, 11:44:16 PM] INFO [ 'NNIManager received command from dispatcher: ID, ' ]
[5/5/2020, 11:44:16 PM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 0, "parameter_source": "algorithm", "parameters": {"users_embedding_dim": 16, "items_embedding_dim": 16}, "parameter_index": 0}' ]
[5/5/2020, 11:44:16 PM] INFO [ 'NNIManager received command from dispatcher: TR, {"parameter_id": 1, "parameter_source": "algorithm", "parameters": {"users_embedding_dim": 4, "items_embedding_dim": 4}, "parameter_index": 0}' ]
[5/5/2020, 11:44:21 PM] INFO [ 'submitTrialJob: form: {"sequenceId":0,"hyperParameters":{"value":"{\\"parameter_id\\": 0, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"users_embedding_dim\\": 16, \\"items_embedding_dim\\": 16}, \\"parameter_index\\": 0}","index":0}}' ]
[5/5/2020, 11:44:26 PM] INFO [ 'submitTrialJob: form: {"sequenceId":1,"hyperParameters":{"value":"{\\"parameter_id\\": 1, \\"parameter_source\\": \\"algorithm\\", \\"parameters\\": {\\"users_embedding_dim\\": 4, \\"items_embedding_dim\\": 4}, \\"parameter_index\\": 0}","index":0}}' ]
```

 - [nnictl stdout and stderr](https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/Nnictl.md#nnictl%20log%20stdout) : 

`nnictl log stderr` and `nnictl log stdout` are both empty other than the experiment start time

**Comment by SparkSnail** [comment]
Hi @seanytak, does your AKS has any pod running about frameworkController? Could you please show your NNI's experiment configuration here?

**Comment by seanytak** [comment]
Hi @SparkSnail , when I run `kubectl get pods` I have the `frameworkcontroller-0` pod running. My NNI experiment configuration is below
```
authorName: setakafu
experimentName: recommenders_ncf
trialConcurrency: 2
maxExecDuration: 1h
maxTrialNum: 20
#choice: local, remote, pai, kubeflow
trainingServicePlatform: frameworkcontroller
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
assessor:
  builtinAssessorName: Medianstop
  classArgs:
    optimize_mode: maximize
trial:
  codeDir: .
  taskRoles:
    - name: worker
      taskNum: 1
      command: python3 train_ncf.py
      gpuNum: 1
      cpuNum: 1
      memoryMB: 8192
      image: msranni/nni:latest
      frameworkAttemptCompletionPolicy:
        minFailedTaskCount: 1
        minSucceededTaskCount: 1
frameworkcontrollerConfig:
  storage: azureStorage
  keyVault:
      vaultName: "nni"
      name: "nnikey"
  azureStorage:
      accountName: "nnistorage"
      azureShare: "ncf"
```

I'm unsure how to submit a normal job to frameworkController without NNI any help on this would be greatly appreciated. Also something I should add is that I  am not sure if KUBE_APISERVER_ADDRESS and KUBECONFIG needed to be given a value in the framework controller yaml below:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frameworkcontroller
  namespace: default
spec:
  serviceName: frameworkcontroller
  selector:
    matchLabels:
      app: frameworkcontroller
  replicas: 1
  template:
    metadata:
      labels:
        app: frameworkcontroller
    spec:
      # Using the service account with granted permission
      # if the k8s cluster enforces authorization.
      serviceAccountName: frameworkcontroller
      containers:
      - name: frameworkcontroller
        image: frameworkcontroller/frameworkcontroller
        # Using k8s inClusterConfig, so usually, no need to specify
        # KUBE_APISERVER_ADDRESS or KUBECONFIG
        #env:
        #- name: KUBE_APISERVER_ADDRESS
        #  value: {http[s]://host:port}
        #- name: KUBECONFIG
        #  value: {Pod Local KubeConfig File Path}
```

**Comment by SparkSnail** [comment]
Hi @seanytak , does your cluster enables RBAC? did you create a service account for frameworkcontroller? https://github.com/Microsoft/frameworkcontroller/tree/master/example/run#run-by-kubernetes-statefulset. After you create the service account, you could set  you frameworkControllerConfig in NNI as:
```
frameworkcontrollerConfig:
  storage: azureStorage
  serviceAccountName: frameworkbarrier
  keyVault:
      vaultName: "nni"
      name: "nnikey"
  azureStorage:
      accountName: "nnistorage"
      azureShare: "ncf"
```
Just try it.
