### ISSUE TITLE
QUniform distribution produces incorrect search space

### ISSUE THREAD

**Issue by mstfbl** [microsoft/nni#2974]
**Environment**:
- NNI version: 1.8
- NNI mode (local|remote|pai): local
- Client OS: Linux
- Server OS (for remote mode only):
- Python version: 3.8
- PyTorch/TensorFlow version: Both
- Is conda/virtualenv/venv used?: conda is used
- Is running in Docker?: No

**Log message**:
 - nnimanager.log: N/a
 - dispatcher.log: N/a
 - nnictl stdout and stderr: N/a
 
 N/a

**What issue meet, what's expected?**:
The incorrect search space was produced when given the `quniform` distribution with values `(0.2, 0.8, 0.3)`. It produced the values `{0.2, 0.3, 0.8}`. I expected it to produce  `{0.2, 0.5, 0.8}`. Is this expected behavior for `quniform`, or would you say there is a bug in how the search space is generated? If it's the former, does NNI have a distribution type that would yield the search space I expected? Thanks.

**How to reproduce it?**: 
`search_space.json`
```json
{
    "x":{"_type":"quniform", "_value":[0.2, 0.8, 0.3]}
}
```
`config.yml`
```yml
authorName: default
experimentName: quadratic_optimization_nni
trialConcurrency: 4
maxExecDuration: 100h
maxTrialNum: 100
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: Random
trial:
  command: python3 main.py
  codeDir: .
  gpuNum: 1
localConfig:
  maxTrialNumPerGpu:  2
```
`quadratic_nni.py`
```python
import torch
import nni

def main():
    torch.manual_seed(0)
    best_fx = float("inf")
    best_x = 0
    for i in range(1, 101):
        x = nni.get_next_parameter()
        fx = (x-2)**2
        nni.report_intermediate_result(fx)
        if fx < best_fx:
            best_fx = fx
            best_x = x
    nni.report_final_result(best_fx)
    
    print("NNI Results:")
    print("\tBest found hp: ", best_x)
    print("\tBest found f(x): ", best_fx)

if __name__ == '__main__':
    main()
```
**Additional information**:

![nni_quniform_bug](https://user-images.githubusercontent.com/5262061/96305559-efff1880-0fb2-11eb-9176-c5dc7eb4b6c3.PNG)
