### ISSUE TITLE
The example nni/examples/trials/mnist-tfv2 don‘t use the gpu

### ISSUE THREAD

**Issue by JohanOu** [microsoft/nni#3331]
when I test the mnist-tfv2，it can start and complete the experiment successfully，but I find that when it was running,it didn't use the gpu,I use nvidia-smi to see the gpu infomation but don't find any process using it.
But when i test the code written by myself,the gpu works.
![image](https://user-images.githubusercontent.com/64004740/105638563-28659b00-5eae-11eb-82cf-c3d62d0b3730.png)
![image](https://user-images.githubusercontent.com/64004740/105638593-5d71ed80-5eae-11eb-9e74-ad36f7dec611.png)

**Comment by J-shang** [comment]
By default in `examples/trials/mnist-tfv2/config_xxx.yml`, we set:
```
trial:
  command: python3 mnist.py
  codeDir: .
  gpuNum: 0
```
means we don't use GPU for trials.

If GPU is needed, you can set:
```
trial:
  command: python3 mnist.py
  codeDir: .
  gpuNum: 1
```
means one trial use one GPU.
