### ISSUE TITLE
Conversion from v2 format failed

### ISSUE THREAD

**Issue by risemeup** [microsoft/nni#3342]
**Environment**:
- NNI version: 2.0
- NNI mode (local|remote|pai): remote
- Client OS: win10
- Server OS (for remote mode only): ubuntu 18.04
- Python version: 3.6
- PyTorch/TensorFlow version: tensorflow1.13.1
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: No

**Log message**:
 - nnimanager.log: 
 - dispatcher.log:
 - nnictl stdout and stderr:
 ```
(BOHB) D:\python_project\nni>nnictl create --config examples/trials/mnist-annotation/config_remote1.yml
INFO:  expand codeDir: . to D:\python_project\nni\examples\trials\mnist-annotation\.
WARNING: Validation with V1 schema failed. Trying to convert from V2 format...
ERROR: Conversion from v2 format failed: RuntimeError('Unsupported Training service configuration!',)
ERROR: Config in v1 format validation failed. SchemaError('This machine does not contain eth0 network device, please set nniManagerIp in config file!',)
```
 

**What issue meet, what's expected?**:

**How to reproduce it?**: 
my system is win10 and want to run it on ubuntu 18.04 by remote mode.I follow [this](https://nni.readthedocs.io/en/latest/TrainingService/RemoteMachineMode.html) doc to start object. But I got wrong message above when I run the command `create --config examples/trials/mnist-annotation/config_remote1.yml`
**Additional information**:
`config_remote1.yml` was changed from `examples/trials/mnist-annotation/config_remote.yml`. I add `ip`,`username`,`passwd`,`port` and `preCommand` about remote machine.
```
authorName: default
experimentName: example_mnist
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: remote
#choice: true, false
useAnnotation: true
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python3 mnist.py
  codeDir: .
  gpuNum: 0
#machineList can be empty if the platform is local
machineList:
  - ip: 47.xx.x.xxx
    username: xxx
    passwd: xxxx
    #port can be skip if using default ssh port 22
    port: 6003
    preCommand: source /home/vv/anaconda3/bin/activate py_test
```
