### ISSUE TITLE
Resume or view experiment from logDir

### ISSUE THREAD

**Issue by shen338** [microsoft/nni#3431]
Thank you for this amazing repo. It's SO helpful! 

Right now, I am running NNI experiment inside docker. But my docker server tends to crash from time to time. Once it crashes, I basically lost everything. After changing the logDir outside the docker, I can save the raw results, but it's tedious to view all the trials one by one to see the final result. 

Also I cannot resume the experiment after docker is crashed. Seems like I lost the metadata in nnictl considering this: 

In https://github.com/microsoft/nni/issues/2509, the author said: 
> nnictl has a metadata folder under ~/.local/nnictl, you should also copy the sub-folders under this metadata folder, and merge the two ~/.local/nnictl/.experiment file to one file in your machine B.

But I cannot find this ~/.local/nnictl/ folder inside the docker. If I can get this metadata, I am probably able to resume the experiment. 

**What would you like to be added**:

A way to resume experiment with only a logDir folder after docker crashes. I know this might be hard, but is this possible? If not, is there any other meta files I need to save in order to resume the experiment? 

If this is not possible, a way to visualize experiment result with only the logDir folder would also be great. 

**Why is this needed**:

Necessary to resume the experiment if the environment, like docker, is crashed

**Without this feature, how does current nni work**：

It works great! I believe there is a work-around to resume the experiment, but I cannot figure out how to do so. 

**Components that may involve changes and Brief description of your proposal if any**:

Not really familiar with the source code. So no opinion here

**Comment by J-shang** [comment]
@shen338 Hi, We will deprecate `~/.local/nnictl` since `v2.1`. After `v2.1`, we will use `~/experiments/.experiment` and `~/experiments/EXPERIMENT_ID/db/nni.sqlite` to `resume` or `view` experiment. So in `v2.1`, you can add experiment metadata manully following the `~/experiments/.experiment` format, and in this metadata, you can specify the `logDir`.
But I think maybe you can treat your docker as a remote training service? In that case, maybe you can avoid these troubles.
https://nni.readthedocs.io/en/stable/TrainingService/RemoteMachineMode.html

**Comment by shen338** [comment]
Thank you for the quick reply! So I only need to wait for v2.1 then. After v2.1, the metadata will also be saved to logDir, which I can specify. 

Actually, the docker is a remote docker. Right now I am doing ssh tunneling through local machine to remote, like this: ssh -L localhost:8080:localhost:8080 name@ip. Also opening docker port 8080 to see WebUI with a command like this: docker run -p 8080:8080 ....

In this way, do you think it's possible to run NNI in a remote fashion? If so, I would love to leverage it

**Comment by J-shang** [comment]
Yes, I think directly use remote training service and config ip, port, username and password in NNI config should work. 

This means maybe you can install NNI on your local machine, then config your docker container ssh service, and run `docker run -p 20022:22 ...` if using the default ssh port `22`. Then set NNI config:

```
trainingServicePlatform: remote
machineList:
  - ip: {your-remote-machine-host}
    port: 20022
    username: {your-docker-container-username}
    passwd: {your-docker-container-password}
```
Now, you can `nnictl create -c CONFIG_PATH` on your local machine.

**Comment by shen338** [comment]
Thank you for the suggestion! That's great! I also found the tutorial here: https://nni.readthedocs.io/en/stable/Tutorial/HowToUseDocker.html. I never use the remote docker like this before

Since there is no detailed code example, I want to elaborate more on this to make sure my understanding is correct. 

For example, my remote IP address is 127.1.1.1 and my user name is eminem. I would like to use port 20022 in my remote machine and port 8000 inside the docker. Here are the steps I can think of: 

1. Build a docker contain in the remote machine. Command like this: `docker run -dit -p 20022:8000 nni_image`
2. Set up config.yml like this: 
```
trainingServicePlatform: remote
machineList:
  - ip: 127.1.1.1
    port: 20022
    username: eminem
    passwd: $<mypasswordto127.1.1.1>$
```
3. After these, launch the experiment locally by `nnictl create -c CONFIG_PATH`

Am I correct on these steps? 

I was also thinking about running experiments remotely, my naive thought is following this tutorial: https://nni.readthedocs.io/en/stable/TrainingService/RemoteMachineMode.html. Like how to launch experiments in conda environment, can I use some preCommand to first execute a docker container and then run experiments? The code would be like this: 

```
machineList:
  - ip: ${replace_to_your_remote_machine_ip}
    username: ${replace_to_your_remote_machine_username}
    sshKeyPath: ${replace_to_your_remote_machine_sshKeyPath}
    # Pre-command will be executed before the remote machine executes other commands.
    # Below is an example of specifying python environment.
    # If you want to execute multiple commands, please use "&&" to connect them.
    # preCommand: source ${replace_to_absolute_path_recommended_here}/bin/activate
    # preCommand: source ${replace_to_conda_path}/bin/activate ${replace_to_conda_env_name}
    preCommand: docker exec -it nni_container bash
```

Would this work as well?

**Comment by J-shang** [comment]
I think the config should be:
```
trainingServicePlatform: remote
machineList:
  - ip: 127.1.1.1
    port: 20022
    username: $<docker container username>$
    passwd: $<mypasswordto docker container>$
```
Usually, maybe you use the username `root` as default container user, and maybe you need to set root passwd at first in the container. Remember the username and password are for the container in this case.

For the second way, it won't work because we don't support interactive commands.
