### ISSUE TITLE
Problem about the nni k8s service

### ISSUE THREAD

**Issue by xieydd** [Microsoft/nni#361]
I deployment the nni as a service in k8s cluster, but when i run a experiment successfully, and i can see the log of trial, it has the accuracy. but the dashboard show all trial accuracy is 0,and the metric in dashboard is NaN.
@QuanluZhang

**Comment by QuanluZhang** [comment]
you have to make the port (default 8080) of nni restserver/webui available outside k8s.

**Comment by xieydd** [comment]
@QuanluZhang Can i change the default port of restserver/webui， if i can , where is the config? Thanks a lot.

**Comment by QuanluZhang** [comment]
please run command `nnictl create --help`, it shows how to set port.

**Comment by xieydd** [comment]
@QuanluZhang  I got it . Thanks for you reply.

**Comment by xieydd** [comment]
@QuanluZhang When i set the same port of nnictl port and service port , but the same problem .

**Comment by yds05** [comment]
Hi, @xieydd , do you use ReplicaSet to launcher NNI pod? If yes, could you please also paset your resource definition file for that ReplicaSet? Thanks.

**Comment by xieydd** [comment]
@yds05  I use the deployment.
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nni
  labels:
    app: nni
spec:
  replicas: 1   
  template:
    metadata:
      labels:
        app: nni
    spec:
      containers:
      - image: nni:latest
        name : nni
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
        command: 
          - sleep
          - 360d
        ports:
            containerPort: 30018
```
