### ISSUE TITLE
tunerGpuIndices may not work

### ISSUE THREAD

**Issue by jianliu-ml** [microsoft/nni#3839]
In v2.3, I use the following config:

useAnnotation: true
trialCommand: python train.py
trialCodeDirectory: .
trialGpuNumber: 1
trialConcurrency: 2
maxTrialNumber: 10
maxExperimentDuration: 1h
`tunerGpuIndices: 5,6`
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: false

And train.py only specifies `device = 'cuda'`.

When the trial is created, it runs on GPU0 and GPU1 insteand of GPU5 and GPU6

**Comment by cruiseliu** [comment]
You need to specify trial GPU indices in this case.
```
trainingService:
    platform: local
    useActiveGpu: false
    gpuIndices: 5,6
```
