### ISSUE TITLE
NNI frameworkcontroller example, data path mount

### ISSUE THREAD

**Issue by mf-giwoong-lee** [microsoft/nni#4170]
**Describe the issue**:
[https://nni.readthedocs.io/en/stable/TrainingService/FrameworkControllerMode.html](url)

I followed this above example and found that there are no data path in this example.

The example downloads the data through tensorflow example library.

In real world, training neural networks need bunch of data but this example and nni frameworkcontroller have any no description for data utilization.

Is there any way to add data path to nni config in NNI frameworkcontroller?

This is example config for NNI frameworkcontroller
```
authorName: default
experimentName: example_mnist
trialConcurrency: 1
maxExecDuration: 10h
maxTrialNum: 100
#choice: local, remote, pai, kubeflow, frameworkcontroller
trainingServicePlatform: frameworkcontroller
searchSpacePath: ~/nni/examples/trials/mnist-tfv1/search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
assessor:
  builtinAssessorName: Medianstop
  classArgs:
    optimize_mode: maximize
trial:
  codeDir: ~/nni/examples/trials/mnist-tfv1
  taskRoles:
    - name: worker
      taskNum: 1
      command: python3 mnist.py
      gpuNum: 1
      cpuNum: 1
      memoryMB: 8192
      image: msranni/nni:latest
      frameworkAttemptCompletionPolicy:
        minFailedTaskCount: 1
        minSucceededTaskCount: 1
frameworkcontrollerConfig:
  storage: nfs
  nfs:
    server: {your_nfs_server}
    path: {your_nfs_server_exported_path}
```

**Environment**:
- NNI version: 2.4
- Training service (local|remote|pai|aml|etc): frameworkcontroller
- Client OS: 
- Server OS (for remote mode only):
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by SparkSnail** [comment]
You could put your data in nfs path, the path will mount into k8s container, you could read the data in the container.
```
frameworkcontrollerConfig:
  storage: nfs
  nfs:
    server: {your_nfs_server}
    path: {your_nfs_server_exported_path}
```
