### ISSUE TITLE
[Question] Add trial

### ISSUE THREAD

**Issue by fsmosca** [microsoft/nni#4181]
Is there a way to add a trial, for example when using GPTuner, with para1=10, param2=70 and objective_value=0?

**Comment by liuzhe-lz** [comment]
You can click "customized trial" button on web UI to manually add a trial.
However GPTuner will not receive metrics from manually added trials. This is a limitation of the tuner implementation.

![customized-trial](https://user-images.githubusercontent.com/40699903/133385039-54e806f1-fb6d-4e8c-9dd4-b83e18baa22f.png)

**Comment by fsmosca** [comment]
How about for the advisor?

```
advisor:
  builtinAdvisorName: BOHB
  classArgs:
    optimize_mode: maximize
    min_budget: 1
    max_budget: 27
    eta: 3
```
