### ISSUE TITLE
could nni let >2 tasks run on one GPU at the same time?

### ISSUE THREAD

**Issue by DavideHe** [microsoft/nni#4195]
**Describe the issue**:
I have a expriment,the model is light, run nvidia T4 GPU. Normally, one GPU can run 4 task at the same time.
so I set the trialConcurrency=4; maxTrialNumPerGpu=4;  gpuNum=1;
when run the first 4 tasks, the expriment stops.I wait a long time,no new task run.
Then  I set trialConcurrency=1; maxTrialNumPerGpu=1;  gpuNum=1;
expriment can run new task, when the first task finished.

**Environment**:
- NNI version: 2.0
- Training service (local|remote|pai|aml|etc):
- Client OS:
- Server OS (for remote mode only): 
- Python version: 3.6
- PyTorch/TensorFlow version: PyTorch1.2
- Is conda/virtualenv/ venv used?:
- Is running in Docker?: Yes

**How to reproduce it?**:

**Comment by DavideHe** [comment]
I found this maybe because I run this expriment on dorcker. I later run it well on a real machine .

**Comment by Fiascolsy** [comment]
Would you like to share us the version of docker image? I will try it in docker ASAP.

**Comment by DavideHe** [comment]
> Would you like to share us the version of docker image? I will try it in docker ASAP.

docker will not be shared because it is not pulled  common docker hub.
but i can provide the linux version and kernel version , other key  lib info:
Linux version 4.9.99 (gcc version 6.3.0 (GCC) ) #1 SMP Mon Oct 21 14:47:51 CST 2019  
Ubuntu 18.04.3 LTS
other key libs:
torch 1.2  (cuda 10.0)
torchvision 0.4.0
tensorboard 1.14.0
nni 2.0 and 2.4 i tried 
scipy 1.2.1

**Comment by Fiascolsy** [comment]
Thank you. And I wonder if you run the experiment with a config file like '*.yaml'? If you do, please share me a copy with that : )

**Comment by DavideHe** [comment]
> Thank you. And I wonder if you run the experiment with a config file like '*.yaml'? If you do, please share me a copy with that : )
config.yml , as below:
```
experimentName: xxxx
trialConcurrency: 2
maxExecDuration: 1d
maxTrialDuration: 1h    ## nni=2.4
maxTrialNum: 1000
#choice: local, remote, pai, kubeflow
trainingServicePlatform: local
searchSpacePath: search_space.json
# logDir: xxxxx/temp/nni-experiments/  
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
assessor:
  builtinAssessorName: Medianstop
  classArgs:
    optimize_mode: minimize
trial:
  command: python train.py
  codeDir: .
  gpuNum: 1
localConfig:
  gpuIndices: "0"
  maxTrialNumPerGpu: 2
  useActiveGpu: true
```
