### ISSUE TITLE
nni's trial can only use global python in remote mode

### ISSUE THREAD

**Issue by Crysple** [Microsoft/nni#424]
I ran an example in remote mode and trials all failed. The trial log in the remote machine showed that it could not import nni
Then I found that nni will only use global python3 (usr/bin/python3) in remote machines to start a trial, but I install nni sdk locally

**Comment by leelaylay** [comment]
My sugguestion is that in your config_remote.yml you can add point out the prthon interpreter explictly.

```yaml
trial:
  # for example /home/yourname/anaconda3/bin/python
  command: /path/to/python XXX.py
  codeDir: .
  gpuNum: 1
```
