### ISSUE TITLE
How can I upgrade my Config from V1 to V2 ?

### ISSUE THREAD

**Issue by explain116** [microsoft/nni#4359]
**Describe the issue**:
I have already run `python3 -m pip install --upgrade nni`, upgrade nni from 2.4 to 2.5 .
However, though It shows that my version is 2.5 when I run `nnictl --version`, it seems that my Config version is only V1 because when I use 
```python
trainingService:
  platform: local
  useActiveGpu: false 
```
and run `nnictl create --config search.yml -p 8080`, it says `ERROR: Config V1 validation failed: SchemaWrongKeyError("Wrong key 'trainingService' in .......`

**Environment**:
- NNI version: 2.5
- Training service (local|remote|pai|aml|etc): local
- Client OS: Ubuntu
- Server OS (for remote mode only):
- Python version: 3.8.11
- PyTorch version: 1.7.1
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

my search.yml is as follows:
```yaml
authorName: test
experimentName: test_search
trialConcurrency: 6
maxExecDuration: 24h
maxTrialNum: 100
trainingServicePlatform: local
searchSpacePath: search_space.json 
useAnnotation: false

localConfig:
  useActiveGpu: true
  gpuIndices: 0,1
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize

trial:
  command: python test_nni.py
  codeDir: .
  gpuNum: 1
  
trainingService:
  platform: local
  useActiveGpu: false 
  
```

I wanna know how can I upgrade Config to V2, or how can I run multiple trials on one GPU in Config V1?

Thanks a lot!

**Comment by cruiseliu** [comment]
You are mixing two schemas. The reference of latest format is [here](https://nni.readthedocs.io/en/stable/reference/experiment_config.html).

Your config should look like this in v2:
``` yaml
experimentName: test_search
trialConcurrency: 6
maxExperimentDuration: 24h
maxTrialNumber: 100
searchSpaceFile: search_space.json 

tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize

trialCommand: python test_nni.py
trialGpuNumber: 1
  
trainingService:
  platform: local
  useActiveGpu: false
  gpuIndices: 0,1
```
