### ISSUE TITLE
How to utilize shared memory for pytorch dataloader when running NNI with Frameworkcontroller?

### ISSUE THREAD

**Issue by mf-giwoong-lee** [microsoft/nni#4424]
**Describe the issue**:
I know that k8s uses default shared memory size as 64MB. 

NNI_config.yaml doesn't accept shared memory size value. So how to raise the shared memory size?

It is my main question.

Just you know, `memorySizeMB` doesn't affect the shared memory size.

**Environment**:
- NNI version: 2.5
- Training service (local|remote|pai|aml|etc): frameworkcontroller
- Client OS: ubuntu 18.04
- Server OS (for remote mode only): ubuntu 18.04
- Python version:
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?:
- Is running in Docker?:

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:

**Comment by SparkSnail** [comment]
NNI only support basic configuration for frameworkcontroller, for customized configs, you need to edit the request body in NNI source code and build NNI in your local machine, https://github.com/microsoft/nni/blob/master/ts/nni_manager/training_service/kubernetes/frameworkcontroller/frameworkcontrollerTrainingService.ts#L526, https://github.com/microsoft/nni/blob/master/docs/en_US/Tutorial/InstallationLinux.rst#build-wheel-package-from-nni-source-code.

**Comment by SparkSnail** [comment]
NNI also support merge frameworkcontroller yaml config, you could set your advanced config and set the config path in `configPath`, refer https://github.com/microsoft/nni/blob/master/docs/en_US/TrainingService/FrameworkControllerMode.rst#example

**Comment by SparkSnail** [comment]
NNI is an integration platform for many kinds of training platforms, it could not support all configurations for those platforms immediately, we could consider adding your configuration request in the future, but the priority maybe low, if you are interested with NNI, welcome you to contribute the feature to NNI and make it stronger.

**Comment by mf-giwoong-lee** [comment]
Thanks to reply.

[https://github.com/microsoft/nni/blob/master/docs/en_US/TrainingService/FrameworkControllerMode.rst#example](url)

Some links like `fc_template.yml` is not found in this repository. I think that it is removed..

Can I see that?

**Comment by mf-giwoong-lee** [comment]
I find it!

**Comment by mf-giwoong-lee** [comment]
I am trying to use `configPath` as you mentioned.

I revise the volume specification from pvc to nfs but it is not working.

```
Error: frameworkcontroller trial config is not initialized
    at FrameworkControllerTrainingService.generateContainerPort (/usr/local/lib/python3.6/dist-packages/nni_node/training_service/kubernetes/frameworkcontroller/frameworkcontrollerTrainingService.js:301:19)
    at FrameworkControllerTrainingService.submitTrialJob (/usr/local/lib/python3.6/dist-packages/nni_node/training_service/kubernetes/frameworkcontroller/frameworkcontrollerTrainingService.js:151:14)
    at async NNIManager.manageTrials (/usr/local/lib/python3.6/dist-packages/nni_node/core/nnimanager.js:600:44)
    at async Promise.all (index 3)
    at async NNIManager.run (/usr/local/lib/python3.6/dist-packages/nni_node/core/nnimanager.js:624:9) {
  cause: Error: frameworkcontroller trial config is not initialized
      at FrameworkControllerTrainingService.generateContainerPort (/usr/local/lib/python3.6/dist-packages/nni_node/training_service/kubernetes/frameworkcontroller/frameworkcontrollerTrainingService.js:301:19)
      at FrameworkControllerTrainingService.submitTrialJob (/usr/local/lib/python3.6/dist-packages/nni_node/training_service/kubernetes/frameworkcontroller/frameworkcontrollerTrainingService.js:151:14)
      at async NNIManager.manageTrials (/usr/local/lib/python3.6/dist-packages/nni_node/core/nnimanager.js:600:44)
      at async Promise.all (index 3)
      at async NNIManager.run (/usr/local/lib/python3.6/dist-packages/nni_node/core/nnimanager.js:624:9)
}
```
It is stderr logs.

```
authorName: default
experimentName: electrocity
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
logLevel: trace
#choice: local, remote, pai, kubeflow
trainingServicePlatform: frameworkcontroller
searchSpacePath: <my search space>
#choice: true, false
useAnnotation: false
advisor:
    builtinAdvisorName: BOHB
    classArgs:
        max_budget: 9
        min_budget: 1
        eta: 3
        optimize_mode: minimize
trial:
    codeDir: <my code>
frameworkcontrollerConfig:
    configPath: fc_template.yml
    storage: nfs
    namespace: "default"
    nfs:
        server: <ip>
        path: <my path>
```
It is config.yml

```
apiVersion: frameworkcontroller.microsoft.com/v1
kind: Framework
metadata:
  name: electrocity
  namespace: default
spec:
  executionType: Start
  retryPolicy:
    fancyRetryPolicy: true
    maxRetryCount: 5
  taskRoles:
  - name: worker
    taskNumber: 1
    frameworkAttemptCompletionPolicy:
      minFailedTaskCount: 1
      minSucceededTaskCount: 1
    task:
      retryPolicy:
        fancyRetryPolicy: false
        maxRetryCount: 0
      podGracefulDeletionTimeoutSec: 900
      pod:
        spec:
          restartPolicy: Never
          hostNetwork: false
          containers:
          - name: electrocity-test
            image: mofldocker/ts_engine:nni2.5
            command: ["/bin/bash", "-c"]
            args: ["ls; cd /dev; df -h"]
            ports:
            - containerPort: 5001
            volumeMounts:
            - name: frameworkbarrier-volume
              mountPath: /mnt/frameworkbarrier
            - name: data-volume
              mountPath: /tmp/mount
            - name: shm-vol
              mountPath: /dev/shm
          imagePullSecrets:
          - name: regcred
          serviceAccountName: frameworkbarrier
          initContainers:
          - name: frameworkbarrier
            image: frameworkcontroller/frameworkbarrier
            volumeMounts:
            - name: frameworkbarrier-volume
              mountPath: /mnt/frameworkbarrier
          volumes:
          - name: frameworkbarrier-volume
            emptyDir: {}
          - name: data-volume
            nfs:
              server: <ip>
              path: <my path>
          - name: shm-vol
            emptyDir:
              medium: Memory
```

It is my fc_template.yml
