### ISSUE TITLE
如何提高running里的trail数量？

### ISSUE THREAD

**Issue by FireDragon00** [microsoft/nni#4658]
## NNI 学生项目问题概述 
现在我能在一张显卡上同时运2个trail（一张显卡只能运行2个trail）。

但我想4张显卡同时运行8个trail，我尝试修改了yaml文件里的参数：trialGpuNumber = 4 和 trialConcurrency = 8，这个尝试失败了。

**请简要概述您的问题:**
**通过使用4张显卡，我怎样才能提高running中的trail数量？**

**请提供 NNI 环境信息 :**
**nni Environment :**
- nni version:2.6.1
- nni mode(local|pai|remote):local
- OS:ubuntu
- python version:3.7
- is conda or virtualenv used?:conda
- is running in docker?:NO

**Comment by liuzhe-lz** [comment]
You should set

```yaml
trialConcurrency: 8
trialGpuNumber: 4
trainingService: local
    maxTrialNumberPerGpu: 2
```
