### ISSUE TITLE
How to set independent gpuIndices and maxTrialNumberPerGpu for each machine under remote mode?

### ISSUE THREAD

**Issue by unikcc** [microsoft/nni#5159]
**Describe the issue**:
I want to set specific GPU indices for each machine under NNI's remote mode. 
For example, let machine1 use GPU with index `0` and `1`, and let machine2 use GPU with index `1`, etc.
The detailed setting is as follows.
However, it didn't work at all.
For each machine, no matter what I set, the program will use each GPU card on that machine.
In addition, each card will only run one instance no matter what number the param `maxTrialNumberPerGpu` is set.

**Environment**:
- NNI version: `2.7`
- Training service (local|remote|pai|aml|etc): **remote**
- Client OS: `Ubuntu`
- Server OS (for remote mode only): `Ubuntu`
- Python version: `3.7`
- PyTorch/TensorFlow version: `1.8.2`
- Is conda/virtualenv/venv used?: `Yes`
- Is running in Docker?: `No`

**Configuration**:
 - Experiment config (remember to remove secrets!):

```
experimentName: example_mnist
trialConcurrency: 40
maxExperimentDuration: 8h
maxTrialNumber: 1000
searchSpaceFile: search_space.json
useAnnotation: false
trialCommand: python main.py
trialCodeDirectory: .
trialGpuNumber: 1
useAnnotation: false

tuner:
  name: GridSearch

trainingService:
  platform: remote
  reuseMode: true
  machineList:
  - host: xxx.xx.xx.x
    user: xxx
    ssh_key_file: ~/.ssh/id_rsa
    useActiveGpu: true
    maxTrialNumberPerGpu: 3
    gpuIndices: "1,2"
```
 - Search space:
```json
{
    "pname": {"_type": "choice", "_value": ["0", "1"]},
}

```

**Log message**:
 - nnimanager.log:
 - dispatcher.log:
 - nnictl stdout and stderr:
 

**How to reproduce it?**:
