### ISSUE TITLE
maxTrialNumerPerGpu does not seem to work

### ISSUE THREAD

**Issue by zzzzzx-1115** [microsoft/nni#5235]
**Describe the issue**:
When I tried to train the mnist example in the remote mode, there was always only one trial running in the only GPU I have, and other trials were all waiting. I found several issues like #608 and #2415 mentioned this, and I also set `useActiveGpu` to be `True` and `maxTrialNumberPerGpu` to be greater than 1, but they did not work. Please tell me how to deal with it, thanks!

**Environment**:
- NNI version: 
- Training service (local|remote|pai|aml|etc): remote
- Client OS: Linux
- Server OS (for remote mode only): Linux
- Python version: 3.7.13
- PyTorch/TensorFlow version:
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Configuration**:
config.yaml, where ```test.py``` is the mnist example: 
```
searchSpaceFile: _search_space.json
trialCommand: python3 test.py
trialConcurrency: 16
maxTrialNumber: 64
nniManagerIp: ...
trialGpuNumber: 1 


tuner:
  name: Anneal
  classArgs:
    optimize_mode: maximize

trainingService:
  platform: remote
  machineList:
    - host: 
      user: ubuntu
      ssh_key_file: ...
      pythonPath: /home/ubuntu/anaconda3/envs/pdecoder/bin/
      port: 22
      useActiveGpu: True
      maxTrialNumberPerGpu: 4
      gpuIndices: 0      
```

And the script ```train_nni.py``` used to run the experiment:
```
import nni
from nni.experiment import Experiment
experiment_config = yaml.load(open('config_remote.yaml', 'r'), Loader=yaml.FullLoader)
temp = nni.experiment.ExperimentConfig(None, **experiment_config)
experiment = Experiment(temp)
experiment.run(8888)
```

**How to reproduce it?**: ```python train_nni.py```
