### ISSUE TITLE
Parallel trail lost connection

### ISSUE THREAD

**Issue by leelaylay** [Microsoft/nni#553]
I often lost the connection of parallel trail. Once, I set `trialConcurrency = 4` in `config.yml` but get only one trial in the later time. If you want to know the exact reason, I am pleased to provide the log file.

In addition, would you provide the number of parallel trials which can run at the same time at maximum.

> Google Vizier is scalable to millions of trials per study, thousands of parallel trial evaluations per study, and billions of studies.

**Comment by QuanluZhang** [comment]
Could you provide your config.yml and nnimanager.log? Thanks.

**Comment by leelaylay** [comment]
config.yml:
```yaml
authorName: default
experimentName: example_remote
trialConcurrency: 4
maxExecDuration: 1000h
maxTrialNum: 2000
#choice: local, remote, pai
trainingServicePlatform: remote
#choice: true, false
useAnnotation: false
tuner:
  builtinTunerName: NetworkMorphism
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
    # for now, this tuner only supports cv domain
    task: cv
    #input image width
    input_width: 32
    #input image channel
    input_channel: 3
    #number of classes
    n_output_node: 10
trial:
  command: /home/xxx/anaconda3/bin/python3 cifar10_keras.py
  codeDir: .
  gpuNum: 1
#machineList can be empty if the platform is local
machineList:    
  - ip: x.x.x.x
    username: xxx
    passwd: xxx
```
The `nnimanager.log` file is so huge(more that 1G) that I can not upload it online. There are millions of lines which seems almost the same which may result in the slow rendering of WebUI.
```log
[2018-XX-XXT02:24:54.665Z] INFO null [ 'Set trialjob XXXX status to SUCCEEDED' ]
```
