### ISSUE TITLE
if _name is not defined in HPO space, the experiment will not stop.

### ISSUE THREAD

**Issue by heibaidaolx123** [microsoft/nni#5634]
**Describe the issue**:
When testing nested sub-search-space in HPO, if _name is not defined, the experiment will not stop.

**Environment**:
- NNI version: 2.10
- Training service (local|remote|pai|aml|etc): local
- Client OS: linux
- Server OS (for remote mode only):
- Python version: 3.7
- PyTorch/TensorFlow version: 
- Is conda/virtualenv/venv used?: conda
- Is running in Docker?: no

**Configuration**:
 - Experiment config (remember to remove secrets!):
 - Search space:

**Log message**:
 - nnimanager.log:
 - dispatcher.log: **RuntimeError: '_name' key is not found in this nested search space.**
 - nnictl stdout and stderr:
 

**How to reproduce it?**:
command: `python test_hpo_space.py --space test.yaml`
test_hpo_space.py:
```
import nni
import numpy as np
import torch
import os
import logging
import random
import time
import argparse
import json
import yaml

nni.silence_stdout()
from nni.experiment import Experiment


def run_trial():
    param = nni.get_next_parameter()
    logging.info(f"param: {param}")
    # time.sleep(1)
    nni.report_final_result(random.random())


def main(space: dict):
    experiment = Experiment("local")
    experiment.config.trial_command = f"python test_hpo_space.py run_trial --space 123"

    experiment.config.experiment_name = "HPO"
    experiment.config.trial_code_directory = os.getcwd()
    experiment.config.search_space = space
    experiment.config.tuner.name = "Evolution"
    experiment.config.tuner.class_args["optimize_mode"] = "maximize"
    experiment.config.tuner.class_args["population_size"] = 60
    experiment.config.max_trial_number = 60
    experiment.config.trial_concurrency = 10

    experiment.start(18189, debug=True, run_mode=nni.experiment.RunMode.Background)

    try:
        experiment._wait_completion()
    except KeyboardInterrupt:
        logging.warning("KeyboardInterrupt detected")
    finally:
        experiment.stop()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--space", type=str, required=True)
    args, extra_args = parser.parse_known_args()
    if "run_trial" in extra_args:
        run_trial()
    else:
        space_file = args.space
        try:
            space = json.load(open(space_file))
        except Exception:
            with open(space_file, "r", encoding="utf-8") as f:
                space = yaml.safe_load(f)
        main(space)
```

test.yaml:
```
layer0:
  _type: choice
  _value:
    - Empty
    - kernel_size:
        _type: choice
        _value: [1, 2, 3, 5]
    - _name: Max_pool
      pooling_size:
        _type: choice
        _value: [2, 3, 5]
    - _name: Avg_pool
      pooling_size:
        _type: choice
        _value: [2, 3, 5]
```
