### ISSUE TITLE
CUDA_VISIBLE_DEVICES set to null

### ISSUE THREAD

**Issue by andrewconnors** [Microsoft/nni#995]
Hi!

I'm trying to run a retinanet training with nni and am running into an issue where all my trials fail. When diving deeper into the issue, each one of my trials have the stderr output of:

`RuntimeError: [/opt/dali/dali/util/cuda_utils.h:60] CUDA runtime api error "no CUDA-capable device is detected"`

Diving deeper I see that in the `run.sh` file for the experiment, the CUDA_VISIBLE_DEVICES flag is not set:

```
#!/bin/bash
cd /retinanet/.
export NNI_PLATFORM=local
export NNI_SYS_DIR=/root/nni/experiments/I9RfkzsX/trials/Yut1X
export NNI_TRIAL_JOB_ID=Yut1X
export NNI_OUTPUT_DIR=/root/nni/experiments/I9RfkzsX/trials/Yut1X
export NNI_TRIAL_SEQ_ID=1
export MULTI_PHASE=false
export CUDA_VISIBLE_DEVICES=
eval retinanet train retinanet_rn50fpn.pth --backbone ResNet50FPN --images /coco/images/train2017/ --annotations /coco/annotations/instances_train2017.json --val-images /coco/images/val2017/ --val-annotations /coco/annotations/instances_val2017.json --logdir /project/output/logs/ 2>/root/nni/experiments/I9RfkzsX/trials/Yut1X/stderr
echo $? `date +%s000` >/root/nni/experiments/I9RfkzsX/trials/Yut1X/.nni/state

```

nvidia-smi outputs the following:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   39C    P0    39W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

And I can run the retinanet standalone command without any errors from the command line.

My config file looks like this:
```
authorName: Andrew Connors
experimentName: retinanet_autotune_default
trialConcurrency: 1
maxExecDuration: 4h
maxTrialNum: 10
#choice: local, remote, pai, kubeflow
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: retinanet train retinanet_rn50fpn.pth --backbone ResNet50FPN --images /coco/images/train2017/ --annotations /coco/annotations/instances_train2017.json --val-images /coco/images/val2017/ --val-annotations /coco/annotations/instances_val2017.json --logdir /project/output/logs/
  codeDir: .
  gpuNum: 0
```

I should mention I am running this inside a docker container but I don't see why that might matter.

Thanks in advance for any help!
